export const DOCTOR_SEARCH_REQUEST = 'raskLege/DOCTOR/DOCTOR_SEARCH_REQUEST';
export const DOCTOR_SEARCH_SUCCESS = 'raskLege/DOCTOR/DOCTOR_SEARCH_SUCCESS';
export const DOCTOR_SEARCH_FAILURE = 'raskLege/DOCTOR/DOCTOR_SEARCH_FAILURE';
